//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkComplain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplainStatu
    {
        public ComplainStatu()
        {
            this.Complains = new HashSet<Complain>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Complain> Complains { get; set; }
    }
}
